# Generated by Django 4.1.5 on 2023-01-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('textfield1', models.TextField()),
                ('datetimefield1', models.DateField()),
            ],
        ),
    ]
